# Generated by Django 3.2.12 on 2022-02-12 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0003_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('decimals', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userId',
            new_name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='alias',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
