# Generated by Django 3.2.12 on 2022-02-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0004_auto_20220212_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserWalletsApp.currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserWalletsApp.users')),
            ],
        ),
    ]
