# Generated by Django 3.2.12 on 2022-02-12 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('d', 'deposit'), ('w', 'withdrawl')], max_length=1)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('f', 'failed'), ('s', 'success')], max_length=1)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserWalletsApp.wallet')),
            ],
        ),
    ]
