# Generated by Django 3.2.12 on 2022-02-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0006_auto_20220212_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='createdAt',
        ),
    ]
