# Generated by Django 3.2.12 on 2022-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0007_remove_users_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('dep', 'Deposit'), ('wit', 'withdrawl')], max_length=3),
        ),
    ]
