# Generated by Django 3.2.12 on 2022-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0009_auto_20220213_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
