# Generated by Django 3.2.12 on 2022-02-13 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWalletsApp', '0011_transaction_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='createByDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
